-- ADR 0009 post templates — named, reusable post skeletons with {slots}.
--
-- A template is a post the customer already wrote the *shape* of: "🎙️ New
-- episode {number}: {title}" and so on. They pick it in the composer, hit "Fit
-- to template", and the AI transcribes their raw notes into it — filling each
-- slot from the meaning of what they wrote and leaving every character outside
-- the slots exactly as they typed it. The saved counterpart to the AI buttons
-- beside it, in the same way a hashtag group is the saved counterpart to
-- "Hashtags": one asks a model to invent a shape, this one reuses the shape the
-- customer already decided on.
--
-- This is client + database only, and deliberately so. The one server-side
-- consumer, supabase/functions/ai-assist, receives the template *body* on the
-- request it is already given the customer's text on, and never reads this
-- table. 20260831130000_hashtag_groups.sql stated the principle for its own
-- table — "nothing in supabase/functions/* learns about this table" — and it
-- holds here for a sharper reason: a template body is customer-authored free
-- text that is about to be handed to a language model, so it is *content*. A
-- function that looked the row up would be a function that had authenticated a
-- string into looking trustworthy. It travels as content, is delimited as
-- content, and is refused as content when it is malformed (ADR 0009 §4). No
-- claim RPC changes and the posts status trigger is untouched: by the time a
-- filled-in template is saved it is indistinguishable from anything else the
-- customer typed into the composer.
--
-- SHAPE — a table, not brand jsonb, for exactly the reasons hashtag_groups
-- gave. `brands.connections` and `brands.smartlink` are jsonb because they are
-- one small object per brand that the save_brand RPC already carries. Templates
-- are a *list of independent records* created, renamed, edited and deleted one
-- at a time, like posts and inbox threads. Parking them in brand jsonb would
-- make every template edit a whole-brand write and would put them through
-- save_brand, which is owner-adjacent RPC surface they have no business on. It
-- would also be a worse fit here than there: a body is up to 2000 characters,
-- so twenty of them is a brand row that grows by 40 KB and is rewritten on
-- every rename. So this mirrors public.hashtag_groups column for column — a
-- text primary key generated by the browser, a cascading brand_id, the payload,
-- `client_id` (the realtime echo filter js/remote-store.js writes and reads)
-- and `updated_at`.
--
-- RLS — is_member(brand_id), for all operations, exactly like `hashtag_groups`,
-- `posts_all` and `inbox_all`. ADR 0006 reserves is_owner for the small set of
-- destructive or account-shaped acts: deleting a brand, disconnecting an
-- account, publishing a SmartLink, managing the roster. Composing is everyday
-- editor work and a template is composing equipment — an editor who may write
-- the post may keep the skeleton they write it into. Deletion of the brand
-- takes its templates with it through the foreign key, so there is no orphan
-- path to police.
--
-- SERVER-SIDE VALIDATION SEAM — the same one 20260830120000_post_variants.sql
-- established and 20260831110000_carousel_media.sql and
-- 20260831130000_hashtag_groups.sql reused, for the same reason. Templates are
-- upserted straight from the browser under the policy below, and RLS answers
-- "whose template is this?", not "is this body well-formed?". A CHECK is the
-- one gate every writer passes: today's browser, a future Edge Function, psql,
-- a replayed backup. The predicate has to *count regex matches*, which needs a
-- set-returning function in a FROM clause and therefore a subquery, and a CHECK
-- expression may not contain one — so it delegates to an IMMUTABLE SQL
-- function, exactly as the sibling's array predicate does. The usual caveat
-- applies and is accepted deliberately: changing the function does not
-- re-validate stored rows, so a stricter rule needs its own migration with a
-- `validate constraint` pass.
--
-- PLACEHOLDER SYNTAX, and how this file counts them.
--
-- A placeholder is `{name}` where name is 1..40 characters of [A-Za-z0-9_]:
-- the pattern `\{[A-Za-z0-9_]{1,40}\}`. The braces are escaped because an
-- unescaped `{` opens a bound in a POSIX regular expression. Anything that does
-- not match is not a placeholder and is not treated as one — `{}`, `{first
-- name}` and a lone `{` are ordinary characters that the fill step reproduces
-- verbatim. That is the honest behaviour to state out loud, because a customer
-- who writes `{first name}` should be told their template has no slots rather
-- than be given a slot whose name is a space.
--
-- Placeholders are counted as *occurrences*, not as distinct names. A body that
-- says `{title}` twice counts as two. Two reasons, and they are the same
-- reason twice: it is the number of substitutions the model actually performs,
-- and it is precisely the length of the array `parsePlaceholders()` in
-- js/templates.js returns — so the sentence the customer reads in Settings and
-- the number this constraint enforces are the same number, rather than two
-- numbers that agree until somebody repeats a slot.
--
-- What the body CHECK enforces, and why each limit is the honest one:
--   * 1..2000 characters. A zero-length body is not a skeleton; 2000 is past
--     any network's own caption ceiling (LinkedIn's 3000 is the outlier, and a
--     template is a frame, not the finished post), and it is the parking
--     ceiling that stops a client leaving unbounded text on the row. It is also
--     MAX_TEMPLATE_CHARS in supabase/functions/ai-assist/index.ts, because the
--     body is going to be sent to a model and the two numbers must be one
--     number;
--   * at least one placeholder. A template with no slots is just fixed text:
--     there is nothing for the fill step to do, so the feature would silently
--     hand the customer their own skeleton back and call it an answer. Refusing
--     it here is what makes that failure impossible rather than confusing;
--   * at most 20 placeholders. Twenty holes in one post is already more than a
--     person can supply material for in a composer box, and it is the ceiling
--     that bounds how much a single request asks a model to invent;
--   * no control characters except newline and tab. A template body is
--     multi-line by nature — the line breaks *are* the shape — so unlike a
--     hashtag it cannot simply refuse the whole C0 range. It refuses the rest of
--     it: the body is rendered back into this app, and the whole promise of the
--     feature is that everything outside the slots comes back byte for byte, so
--     a stray C0 character in one is refused rather than repaired. Carriage
--     return is in the refused set on purpose — a textarea's value normalises
--     CRLF to LF, and two spellings of a line break would mean two templates
--     that look identical and produce different output.

create table if not exists public.post_templates (
  id text primary key,
  brand_id text not null references public.brands(id) on delete cascade,
  name text not null check (char_length(name) >= 1 and char_length(name) <= 60),
  body text not null,
  client_id text,
  updated_at timestamptz not null default now()
);

-- How many `{slot}` placeholders this body carries, counting occurrences. Its
-- own function rather than an inlined subquery because the number is a named
-- concept the browser mirrors (parsePlaceholders().length in js/templates.js)
-- and because it is what makes the predicate below readable at a glance.
create or replace function public.count_template_placeholders(v text)
returns integer
language sql
immutable
set search_path = public
as $$
  select coalesce(
    (select count(*) from regexp_matches(coalesce(v, ''), '\{[A-Za-z0-9_]{1,40}\}', 'g')),
    0)::int
$$;

create or replace function public.valid_post_template_body(v text)
returns boolean
language sql
immutable
set search_path = public
as $$
  select v is not null
     and char_length(v) >= 1
     and char_length(v) <= 2000
     and public.count_template_placeholders(v) >= 1
     and public.count_template_placeholders(v) <= 20
     -- The sibling's `~ '[[:cntrl:]]'` test, with the two characters a
     -- multi-line skeleton is made of removed first. translate() is the whole
     -- exception: everything else in the C0 range, DEL included, is refused.
     and translate(v, E'\n\t', '') !~ '[[:cntrl:]]'
$$;

-- The constraint is added after the functions it calls, and dropped first so
-- re-running the migration re-creates it — the shape every sibling CHECK uses.
alter table public.post_templates drop constraint if exists post_templates_body_valid;
alter table public.post_templates
  add constraint post_templates_body_valid
  check (public.valid_post_template_body(body));

alter table public.post_templates enable row level security;

-- Supabase's default privileges hand anon and authenticated everything on a new
-- public table, so the grant is stated in full rather than trimmed. DELETE is
-- granted, unlike public.brand_invites: a template is composing equipment, not
-- an audit trail, and js/remote-store.js deletes a removed template exactly the
-- way it deletes a removed hashtag group, post or inbox thread.
revoke all on public.post_templates from public;
revoke all on public.post_templates from anon;
revoke all on public.post_templates from authenticated;
grant select, insert, update, delete on public.post_templates to authenticated;
grant all on public.post_templates to service_role;

-- The only query this table serves: one brand's templates.
create index if not exists post_templates_brand_idx
  on public.post_templates (brand_id);

-- One policy for all operations, gated on membership — the `hashtag_groups_all`
-- / `inbox_all` shape.
drop policy if exists post_templates_all on public.post_templates;
create policy post_templates_all on public.post_templates for all to authenticated
  using (public.is_member(brand_id)) with check (public.is_member(brand_id));

-- The realtime change feed js/remote-store.js subscribes to is schema-wide, but
-- Supabase only emits for tables in this publication. brands, posts,
-- inbox_threads and hashtag_groups are in it; a synced table that is not would
-- leave a second device showing a template list that no longer exists.
do $$ begin
  alter publication supabase_realtime add table public.post_templates;
exception when duplicate_object then null; end $$;
