-- ADR 0005 publishing depth — hashtag groups (named, reusable tag sets).
--
-- The last unblocked publishing-depth item, and a Metricool-parity feature: a
-- customer keeps "Launch week", "Evergreen" and "Local" as named sets and drops
-- one into a post from the composer instead of retyping fifteen tags.
--
-- This is client + database only. Hashtags reach a provider as ordinary post
-- text, so nothing in supabase/functions/* learns about this table, no claim RPC
-- changes, and the posts status trigger is untouched: a group is a *composer
-- convenience*, and by the time a post is saved its tags are indistinguishable
-- from anything else the customer typed.
--
-- SHAPE — a table, not brand jsonb. `brands.connections` and `brands.smartlink`
-- are jsonb because they are one small object per brand that the save_brand RPC
-- already carries. Hashtag groups are a *list of independent records* that are
-- created, renamed and deleted one at a time, exactly like posts and inbox
-- threads. Parking them in brand jsonb would make every group edit a whole-brand
-- write and would put them through save_brand, which is owner-adjacent RPC
-- surface they have no business on. So this table mirrors the smallest existing
-- synced table, public.inbox_threads, column for column: a text primary key
-- generated by the browser, a cascading brand_id, the payload, `client_id` (the
-- realtime echo filter js/remote-store.js writes and reads) and `updated_at`.
--
-- RLS — is_member(brand_id), for all operations, exactly like `posts_all` and
-- `inbox_all`. ADR 0006 reserves is_owner for the small set of destructive or
-- account-shaped acts: deleting a brand, disconnecting an account, publishing a
-- SmartLink, managing the roster. Composing is everyday editor work, and a
-- hashtag group is composing equipment — an editor who may write the post may
-- keep the tag set they write it with. Deletion of the brand takes its groups
-- with it through the foreign key, so there is no orphan path to police.
--
-- SERVER-SIDE VALIDATION SEAM — the same one 20260830120000_post_variants.sql
-- established and 20260831110000_carousel_media.sql reused, for the same reason.
-- Groups are upserted straight from the browser under the policy below, and RLS
-- answers "whose group is this?", not "is this array well-formed?". A CHECK is
-- the one gate every writer passes: today's browser, a future Edge Function,
-- psql, a replayed backup. The predicate iterates the array's elements and a
-- CHECK expression may not contain a subquery, so it delegates to an IMMUTABLE
-- SQL function. The usual caveat applies and is accepted deliberately: changing
-- the function does not re-validate stored rows, so a stricter rule needs its
-- own migration with a `validate constraint` pass.
--
-- What the tags CHECK enforces, and why each limit is the honest one:
--   * a jsonb *array*, never an object — a group is an ordered list the customer
--     arranged, and the order is what gets appended to the post;
--   * 1..30 entries. A group with no tags is not a group, and thirty is well
--     past what any network rewards (Instagram itself caps a post at 30), so it
--     is the ceiling that stops a client parking unbounded jsonb on the row;
--   * every entry is a string beginning `#`. The composer prepends the `#` for
--     a customer who omits it; this is the gate that stops a non-string or a
--     bare word from ever being stored;
--   * 2..100 characters. One character is just the `#`; a hundred is longer than
--     any platform accepts and is the parking ceiling per tag;
--   * no whitespace *inside* a tag — whitespace is what separates one hashtag
--     from the next, so a tag containing it would silently become two;
--   * no control characters. A tag is rendered back into this app and appended
--     to post text; a C0 character in one is refused rather than repaired.

create table if not exists public.hashtag_groups (
  id text primary key,
  brand_id text not null references public.brands(id) on delete cascade,
  name text not null check (char_length(name) >= 1 and char_length(name) <= 60),
  tags jsonb not null,
  client_id text,
  updated_at timestamptz not null default now()
);

create or replace function public.valid_hashtag_group_tags(v jsonb)
returns boolean
language sql
immutable
set search_path = public
as $$
  select v is not null
     and jsonb_typeof(v) = 'array'
     and jsonb_array_length(v) >= 1
     and jsonb_array_length(v) <= 30
     and not exists (
           select 1
             from jsonb_array_elements(v) as item(value)
            where jsonb_typeof(item.value) <> 'string'
               or left(item.value #>> '{}', 1) <> '#'
               or char_length(item.value #>> '{}') < 2
               or char_length(item.value #>> '{}') > 100
               or item.value #>> '{}' ~ '[[:space:]]'
               or item.value #>> '{}' ~ '[[:cntrl:]]'
         )
$$;

-- The constraint is added after the function it calls, and dropped first so
-- re-running the migration re-creates it — the shape both sibling CHECKs use.
alter table public.hashtag_groups drop constraint if exists hashtag_groups_tags_valid;
alter table public.hashtag_groups
  add constraint hashtag_groups_tags_valid
  check (public.valid_hashtag_group_tags(tags));

alter table public.hashtag_groups enable row level security;

-- Supabase's default privileges hand anon and authenticated everything on a new
-- public table, so the grant is stated in full rather than trimmed. DELETE is
-- granted, unlike public.brand_invites: a hashtag group is composing equipment,
-- not an audit trail, and js/remote-store.js deletes a removed group exactly the
-- way it deletes a removed post or inbox thread.
revoke all on public.hashtag_groups from public;
revoke all on public.hashtag_groups from anon;
revoke all on public.hashtag_groups from authenticated;
grant select, insert, update, delete on public.hashtag_groups to authenticated;
grant all on public.hashtag_groups to service_role;

-- The only query this table serves: one brand's groups.
create index if not exists hashtag_groups_brand_idx
  on public.hashtag_groups (brand_id);

-- One policy for all operations, gated on membership — the `inbox_all` shape.
drop policy if exists hashtag_groups_all on public.hashtag_groups;
create policy hashtag_groups_all on public.hashtag_groups for all to authenticated
  using (public.is_member(brand_id)) with check (public.is_member(brand_id));

-- The realtime change feed js/remote-store.js subscribes to is schema-wide, but
-- Supabase only emits for tables in this publication. brands, posts and
-- inbox_threads are in it; a synced table that is not would leave a second
-- device showing a group list that no longer exists.
do $$ begin
  alter publication supabase_realtime add table public.hashtag_groups;
exception when duplicate_object then null; end $$;
